version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enterprise-backend
    ports:
      - "5000:8080"
    depends_on:
      - redis
      - keycloak
    networks:
      - backend-net

  redis:
    image: redis
    container_name: enterprise-redis
    ports:
      - "6379:6379"
    networks:
      - backend-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: enterprise-keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.2
    container_name: enterprise-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false   # فقط برای توسعه
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - backend-net

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.2
    container_name: enterprise-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://enterprise-elasticsearch:9200
    ports:
      - "5601:5601"
    volumes:
      - kibana_data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge

volumes:
  elastic_data:
    driver: local
  kibana_data:
    driver: local
