version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: EnterpriseAutomation.Api/Dockerfile
    container_name: enterprise-backend
    ports:
      - "5000:8080"
    depends_on:
      - redis
      - keycloak
      - sqlserver
    networks:
      - backend-net

  redis:
    image: redis
    container_name: enterprise-redis
    ports:
      - "6379:6379"
    networks:
      - backend-net

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.3
    container_name: enterprise-keycloak
    command: start-dev
    environment:
      KC_DB: dev-mem
      KC_HTTP_RELATIVE_PATH: /auth
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - backend-net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: enterprise-sql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_strong_password123!"
      ACCEPT_EULA: "Y"
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge