version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enterprise-backend
    ports:
      - "5000:8080"
    depends_on:
      - redis
      - keycloak
    networks:
      - backend-net

  redis:
    image: redis
    container_name: enterprise-redis
    ports:
      - "6379:6379"
    networks:
      - backend-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: enterprise-keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev

  mongo:
    image: mongo:6.0
    container_name: enterprise-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
volumes:
  mongo-data: